---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Leon_.
--- DateTime: 20/12/2024 23:51
--

return {
  update_interval = 60,
  min_scale = 0.45,
  max_scale = 1,
  max_size = 4
}