---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Leon_.
--- DateTime: 29/11/2024 23:59
---

local proxy_container = {
  name = "ii-proxy-container",
  type = "proxy-container",
  draw_inventory_content = false,
  flags                   = {"not-on-map", "not-deconstructable", "not-blueprintable"},
  hidden                  = true,
  hidden_in_factoriopedia = true,
  selection_box           = {{-0.1, -0.1}, {0.1, 0.1}},
  collision_mask          = {
    layers                    = {},
    not_colliding_with_itself = true,
    colliding_with_tiles_only = true,
  },
  selection_priority      = 1,
  remove_decoratives      = "false",
}
data:extend{proxy_container}